### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by linonetwo** [vio/bundle-stats-action#132]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: softprops/action-gh-release@v1, vio/bundle-stats-action@v1.3.0

**Comment by vio** [comment]
@linonetwo thanks for creating the issue!

Fixed by https://github.com/vio/bundle-stats-action/releases/tag/v1.3.4
