### ISSUE TITLE
Multiple bundle path

### ISSUE THREAD

**Issue by linonetwo** [vio/bundle-stats-action#78]
How to use this if I have two bundle stats.json, one in `.webpack/main/stats.json`, another in `.webpack/main/stats.json`

**Comment by vio** [comment]
Hi @linonetwo, are the stats for different webpack compilations or same project and you want to compare?

**Comment by linonetwo** [comment]
I can see what this action do is add this line to the Actions page:

![截屏2021-08-13 下午2 03 49](https://user-images.githubusercontent.com/3746270/129312126-df83382a-e093-47bb-95a9-a21bab3dd700.png)


-- | --
bundle-stats | 1.69 MB

But I actually have main process and renderer process for electron, so there are 2 bundles stats.json generated in two different folder...

**Comment by vio** [comment]
In that case the action should run twice and output different artifacts. This is not possible atm, but [I created a new issue for it](https://github.com/vio/bundle-stats-action/issues/83), I think it will be a useful feature.

I am planning an upgrade soon(the action is still using bundle-stats v2) and will try to have a look at the new input. Let me know if you are interested in providing a PR, it will be welcome! ;)

**Comment by linonetwo** [comment]
The code seems not complicated, but sorry I am working on several projects parallelly...So may not be possible to work on this. But I really appreciate your works, I have followed on your account, thank you again for your works.
